### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by NightRaidGamer** [akinbicer/windows-nt5#1]
Hello, I would like to know if it is possible to compile using visual studio?

**Comment by akinbicer** [comment]
Hi @NightRaidGamer,

Yes, this possibility is available. However, a script needs to be developed for this.

**Comment by akinbicer** [comment]
Of course, there is currently my work available on this topic.

**Comment by NightRaidGamer** [comment]
@akinbicer I have one last request to make to you, could you upload the precompiled windows xp files ready to generate the isos into a separate repository please? is that I'm having several errors when compiling, I've seen other places that teach and other people also have problems with this...

**Comment by akinbicer** [comment]
Of course, there is an active development on this subject right now. An update will be made when complete.

**Comment by NightRaidGamer** [comment]
> Of course, there is an active development on this subject right now. An update will be made when complete.

thanks
